name: the_shavi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  mobile_number: ^3.0.0
  permission_handler: ^11.3.1
  responsive_grid_list: ^1.4.0
  sim_card_info: ^1.0.2
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

